### ISSUE TITLE
Auto-generate locale pluralisation functions

### ISSUE THREAD

**Issue by siame** [rolepoint/pyseeyou#2]
The CLDR provides an XML file (current version can be found in the most recent vXX ZIP downloaded from here: http://cldr.unicode.org/index/downloads, navigate to `core/supplemental/plurals.xml`) listing each of the locales and their respective plurality rules. 

This file is structured so that languages with equivalent rules are even grouped together. The plurality rules are even formatted in accordance with an [expression language](http://unicode.org/reports/tr35/tr35-numbers.html#Plural_rules_syntax), which could be used to parse them quite easily.

This means that we can much more effectively generate the plurality functions from this file, rather than type them all out by hand in `locales.py` and store/update them as and when/if they change.

Ideally this would be a script that generates a working `locales.py` file post/during pip-install, and automatically pulls down and uses the latest CLDR `plurals.xml` file as a base.

**Comment by obmarg** [comment]
I agree with most of this, but mutating the library in pip install is probably not a good idea.  It'd basically defeat the point of pinning your pyseeyou dependency to a specific version if the code behind that version could change whenever a new version of a totally unrelated project came out.  Could lead to:
- Applications that depend on pyseeyou breaking without actually changing anything.
- Difficulty investigating bugs because though someone says they're on v1.0.0 you have no idea which version of the CLDR they're using.
- Possibly some other issues?

**Comment by siame** [comment]
Hardcoding a CLDR version and a minor increment sounds like the way to go then.

**Comment by siame** [comment]
Actually, a CLDR change could make backwards-incompatible changes e.g. if a user specified a replacement string for English with: `one {One thing} other {# things}` and the new CLDR version suddenly came out with a new `many` rule for English, that could break things.

Looks like it might be a major version bump for a different CLDR version then?

**Comment by obmarg** [comment]
Potentially.  Guess we can cross that bridge when we come to it.

**Comment by siame** [comment]
This has been addressed in #9, by using the ruleset generator here: https://github.com/Sasha-Sorokin/pyseeyou-plural-ruleset-generator.
