### ISSUE TITLE
locale support for spanish

### ISSUE THREAD

**Issue by floydding** [rolepoint/pyseeyou#5]
Hi,
    I saw in locale.py pyseeyou does not support Spanish. Is there a plan to add support for Spanish(es)?

thanks

**Comment by siame** [comment]
Hi @floydding,

I understand we're missing a lot of languages, but luckily, they're not too difficult to add!

We have an issue open to address programatically adding pluralisation rules from an XML file (#2, which you're welcome to create a PR against), but if you need Spanish in there now, you're welcome to open a PR just adding that too.

All you need to do is update `locales.py` with a new function for Spanish (because it doesn't look like any of our current functions will do), and then add that to the mapping for `es`. I've uploaded the most recent version (v34) of the CLDR's pluralisation rules that you'll need to refer to here: https://gist.github.com/siame/4e2e74eadbe2530d6e4c57072f8b6cea.

Let me know if you run into any issues!

**Comment by floydding** [comment]
Hi i have submitted pull request for adding support for Spanish. Thanks

**Comment by siame** [comment]
Addressed in #6.
